#!/usr/bin/env python3
# Copyright (C) 2025 the DTVM authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Generate fig4-speedup.tex from the frozen ablation CSV.

Reads the 20reps CSV and emits a TikZ/pgfplots grouped bar chart with
asymmetric 95% CI error bars, B&W hatching patterns for 4 benchmark groups.

Usage:
    python3 csv_to_tikz_bar.py <csv_path> > figures/fig4-speedup.tex
"""

import csv
import sys
from typing import List, Tuple

# ---------- group classification ----------

GROUP_KEYWORDS = {
    "U256-heavy": ["memory_grow", "weierstrudel", "snailtracer"],
    "Hash": ["sha1", "blake2b"],
    "Control-flow": ["jump", "loop", "JUMPDEST"],
}
# "Algorithmic" is the default for anything unmatched.

GROUP_ORDER = ["U256-heavy", "Hash", "Algorithmic", "Control-flow"]

# pgfplots pattern styles (B&W friendly)
GROUP_STYLE = {
    "U256-heavy": "fill=black!20",
    "Hash": "pattern=north east lines",
    "Algorithmic": "pattern=crosshatch",
    "Control-flow": "pattern=dots",
}

GROUP_LABEL_ZH = {
    "U256-heavy": "U256 密集型",
    "Hash": "哈希",
    "Algorithmic": "算术/逻辑",
    "Control-flow": "控制流",
}


def classify(bench: str) -> str:
    """Classify a benchmark into a group by substring match."""
    for group, keywords in GROUP_KEYWORDS.items():
        for kw in keywords:
            if kw in bench:
                return group
    return "Algorithmic"


def short_label(bench: str) -> str:
    """Extract a short label from the full benchmark path.

    e.g. 'external/total/main/blake2b_huff/8415nulls' -> 'blake2b\\_huff/8415n'
    """
    parts = bench.strip("/").split("/")
    # Take last two components
    if len(parts) >= 2:
        contract = parts[-2]
        variant = parts[-1]
    else:
        contract = parts[-1]
        variant = ""

    # Shorten variant names for space
    short_variants = {
        "8415nulls": "8415n",
        "empty": "emp",
        "benchmark": "bench",
        "nfts_rank": "nfts",
        "insufficient_liquidity": "insuf",
        "received": "recv",
        "spent": "spent",
        "nogrow": "nogr",
    }
    variant = short_variants.get(variant, variant)

    # Shorten contract names
    short_contracts = {
        "memory_grow_mload": "mg\\_mload",
        "memory_grow_mstore": "mg\\_mstore",
        "blake2b_huff": "b2\\_huff",
        "blake2b_shifts": "b2\\_shifts",
        "sha1_divs": "sha1\\_d",
        "sha1_shifts": "sha1\\_s",
        "swap_math": "swap\\_m",
        "structarray_alloc": "struct\\_a",
        "snailtracer": "snail",
        "weierstrudel": "weier",
        "signextend": "signext",
        "loop_with_many_jumpdests": "loop\\_jd",
        "jump_around": "jump\\_ar",
        "JUMPDEST_n0": "JDEST",
    }
    contract = short_contracts.get(contract, contract.replace("_", "\\_"))

    if variant:
        return f"{contract}/{variant}"
    return contract


def read_csv(path: str) -> List[dict]:
    """Read the frozen CSV and return rows as dicts."""
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        return list(reader)


def emit_tikz(rows: List[dict]) -> str:
    """Generate the complete TikZ figure as a string."""
    # Parse and group
    entries: List[Tuple[str, str, float, float, float]] = []
    for row in rows:
        bench = row["bench"]
        group = classify(bench)
        sp = float(row["speedup_pct"])
        sp_lo = float(row["speedup_ci_lo_pct"])
        sp_hi = float(row["speedup_ci_hi_pct"])
        entries.append((bench, group, sp, sp_lo, sp_hi))

    # Sort: by group order, then by speedup descending within group
    group_rank = {g: i for i, g in enumerate(GROUP_ORDER)}
    entries.sort(key=lambda e: (group_rank[e[1]], -e[2]))

    # Build per-group coordinate lists
    group_coords = {g: [] for g in GROUP_ORDER}
    x_labels = []
    for idx, (bench, group, sp, sp_lo, sp_hi, ) in enumerate(entries):
        label = short_label(bench)
        x_labels.append(label)
        err_minus = sp - sp_lo  # lower error (positive magnitude)
        err_plus = sp_hi - sp  # upper error (positive magnitude)
        group_coords[group].append((idx, sp, err_minus, err_plus))

    n = len(entries)

    lines = []
    lines.append(r"% Auto-generated by csv_to_tikz_bar.py — do not edit")
    lines.append(r"\begin{figure}[t]")
    lines.append(r"\centering")
    lines.append(r"\begin{tikzpicture}")
    lines.append(r"\begin{axis}[")
    lines.append(r"  width=8.5cm,")
    lines.append(r"  height=6cm,")
    lines.append(r"  ybar,")
    lines.append(r"  bar width=2pt,")
    lines.append(f"  xtick={{0,...,{n - 1}}},")
    lines.append(r"  xticklabels={")

    for i, lbl in enumerate(x_labels):
        comma = "," if i < len(x_labels) - 1 else ""
        lines.append(f"    {{{lbl}}}{comma}")

    lines.append(r"  },")
    lines.append(r"  xticklabel style={rotate=45, anchor=east, font=\tiny},")
    lines.append(r"  x tick label style={rotate=45, anchor=east},")
    lines.append(r"  ylabel={加速比 (\%)},")
    lines.append(r"  ylabel style={font=\small},")
    lines.append(r"  ymin=-5,")
    lines.append(r"  ymax=28,")
    lines.append(f"  xmin=-0.8,")
    lines.append(f"  xmax={n - 0.2},")
    lines.append(r"  ytick={-5,0,5,10,15,20,25},")
    lines.append(r"  grid=major,")
    lines.append(r"  grid style={dashed, gray!30},")
    lines.append(r"  legend style={")
    lines.append(r"    at={(0.5,1.02)},")
    lines.append(r"    anchor=south,")
    lines.append(r"    legend columns=4,")
    lines.append(r"    font=\tiny,")
    lines.append(r"    draw=none,")
    lines.append(r"  },")
    lines.append(r"  clip=false,")
    lines.append(r"]")

    # Zero line
    lines.append(r"")
    lines.append(r"% zero reference line")
    lines.append(
        r"\draw[black, thin] (axis cs:-0.8,0) -- (axis cs:"
        + f"{n - 0.2}" + r",0);"
    )
    lines.append(r"")

    # One \addplot per group using table format for asymmetric error bars
    for group in GROUP_ORDER:
        coords = group_coords[group]
        if not coords:
            continue
        style = GROUP_STYLE[group]
        label_zh = GROUP_LABEL_ZH[group]
        lines.append(f"% group: {group}")
        lines.append(
            r"\addplot["
            + style
            + r", draw=black,"
            + r" error bars/.cd, y dir=both, y explicit,"
            + r" error bar style={thin},"
            + r" error mark options={rotate=90, mark size=1.5pt}"
            + r"]"
        )
        lines.append(r"  table[x=x, y=y, y error minus=ym, y error plus=yp] {")
        lines.append(r"    x y ym yp")
        for x, sp, em, ep in coords:
            lines.append(f"    {x} {sp:.4f} {em:.4f} {ep:.4f}")
        lines.append(r"  };")
        lines.append(f"\\addlegendentry{{{label_zh}}}")
        lines.append(r"")

    lines.append(r"\end{axis}")
    lines.append(r"\end{tikzpicture}")
    lines.append(
        r"\caption{27 个基准上启用/关闭窥孔规则集的加速比"
        r"（95\% 置信区间误差棒，按工作负载类型分组）。}"
    )
    lines.append(r"\label{fig:speedup}")
    lines.append(r"\end{figure}")
    lines.append("")  # trailing newline

    return "\n".join(lines)


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <csv_path>", file=sys.stderr)
        sys.exit(1)

    rows = read_csv(sys.argv[1])
    print(emit_tikz(rows))


if __name__ == "__main__":
    main()
