#!/usr/bin/env python3

import argparse
import json
import pathlib
import sys
from typing import Dict, List, Tuple


def load_rules(path: pathlib.Path) -> Dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def normalize_rule(rule: Dict) -> str:
    stage = rule["stage"]
    pattern_parts: List[str] = []
    for item in rule["pattern"]:
        if "opcode" in item:
            head = f"opcode:{item['opcode']}"
        elif "opcode_any" in item:
            head = "opcode_any:" + ",".join(item["opcode_any"])
        else:
            head = f"predicate:{item['predicate']}"
        requires = item.get("require", [])
        require_key = ",".join(
            f"{req['operand']}:{req['field']}:{sorted(req.items())}"
            for req in requires
        )
        pattern_parts.append(f"{head}[{require_key}]")
    when_parts = ",".join(str(sorted(item.items())) for item in rule.get("when", []))
    return f"{stage}|{pattern_parts}|{when_parts}"


def validate_rules(data: Dict) -> Tuple[List[str], List[str]]:
    report_lines: List[str] = []
    conflicts: List[str] = []
    seen: Dict[Tuple[str, int], str] = {}

    report_lines.append("X86 Cg peephole rule report")
    report_lines.append("==========================")
    report_lines.append("")

    rules = sorted(
        data["rules"],
        key=lambda rule: (rule["stage"], -int(rule["priority"]), rule["name"]),
    )
    for rule in rules:
        signature = normalize_rule(rule)
        key = (signature, int(rule["priority"]))
        if key in seen:
            conflicts.append(
                f"Conflicting rules with the same normalized pattern and priority: "
                f"{seen[key]} vs {rule['name']}"
            )
        else:
            seen[key] = rule["name"]
        report_lines.append(
            f"- {rule['name']} | stage={rule['stage']} | priority={rule['priority']}"
        )

    report_lines.append("")
    if conflicts:
        report_lines.append("Conflicts:")
        for item in conflicts:
            report_lines.append(f"- {item}")
    else:
        report_lines.append("No conflicts detected.")

    return report_lines, conflicts


def emit_file_header() -> List[str]:
    return [
        "// Copyright (C) 2025 the DTVM authors. All Rights Reserved.",
        "// SPDX-License-Identifier: Apache-2.0",
        "// Generated by tools/generate_x86_cg_peephole.py. Do not edit.",
        "",
    ]


def resolve_operand_expr(bind: str, operand: int) -> Tuple[List[str], str]:
    if operand >= 0:
        return (
            [
                f"  if ({bind}.getNumOperands() <= {operand})",
                "    return {miss_return};",
            ],
            str(operand),
        )

    required_operands = -operand
    explicit_count = f"{bind}.getDesc().getNumOperands()"
    operand_expr = f"({explicit_count} - {required_operands})"
    return (
        [
            f"  if ({explicit_count} < {required_operands})",
            "    return {miss_return};",
            f"  if ({bind}.getNumOperands() <= {operand_expr})",
            "    return {miss_return};",
        ],
        operand_expr,
    )


def emit_operand_check(bind: str, req: Dict, miss_return: str) -> List[str]:
    operand = req["operand"]
    field = req["field"]
    guard_lines, operand_expr = resolve_operand_expr(bind, operand)
    guard_lines = [line.format(miss_return=miss_return) for line in guard_lines]
    if field == "reg":
        if "equals_capture" in req:
            capture = req["equals_capture"]
            return guard_lines + [
                f"  if (!{bind}.getOperand({operand_expr}).isReg() ||",
                f"      {bind}.getOperand({operand_expr}).getReg() != {capture})",
                f"    return {miss_return};",
            ]
    if field == "imm":
        if "equals_enum" in req:
            enum_name = req["equals_enum"]
            return guard_lines + [
                f"  if (!{bind}.getOperand({operand_expr}).isImm())",
                f"    return {miss_return};",
                f"  if ({bind}.getOperand({operand_expr}).getImm() != X86::CondCode::{enum_name})",
                f"    return {miss_return};",
            ]
        if "equals_int" in req:
            value = int(req["equals_int"])
            return guard_lines + [
                f"  if (!{bind}.getOperand({operand_expr}).isImm())",
                f"    return {miss_return};",
                f"  if ({bind}.getOperand({operand_expr}).getImm() != {value})",
                f"    return {miss_return};",
            ]
    if field == "is_mbb":
        predicate = "!" if req["equals_bool"] else ""
        return guard_lines + [
            f"  if ({predicate}{bind}.getOperand({operand_expr}).isMBB())",
            f"    return {miss_return};",
        ]
    raise ValueError(f"Unsupported operand requirement: {req}")


def emit_capture(bind: str, capture: Dict, miss_return: str) -> List[str]:
    operand = capture["operand"]
    field = capture["field"]
    name = capture["name"]
    guard_lines, operand_expr = resolve_operand_expr(bind, operand)
    guard_lines = [line.format(miss_return=miss_return) for line in guard_lines]
    if field == "reg":
        return guard_lines + [
            f"  if (!{bind}.getOperand({operand_expr}).isReg())",
            f"    return {miss_return};",
            f"  auto {name} = {bind}.getOperand({operand_expr}).getReg();",
        ]
    if field == "imm":
        return guard_lines + [
            f"  if (!{bind}.getOperand({operand_expr}).isImm())",
            f"    return {miss_return};",
            f"  auto {name} = {bind}.getOperand({operand_expr}).getImm();",
        ]
    raise ValueError(f"Unsupported capture: {capture}")


def emit_instruction_match(rule: Dict) -> List[str]:
    name = rule["name"].replace("-", "_")
    first_bind = rule["pattern"][0]["bind"]
    erases_current = first_bind in rule["action"].get("erase", [])
    miss_return = "GeneratedInstructionRuleResult::NoMatch"
    lines = [
        f"GeneratedInstructionRuleResult match_{name}(CgBasicBlock &MBB, "
        "CgBasicBlock::iterator &MII) {",
    ]
    if len(rule["pattern"]) > 1:
        lines.append("  auto MIE = MBB.end();")
    for index, item in enumerate(rule["pattern"]):
        iterator_name = f"LocalMII{index}"
        bind = item["bind"]
        if index == 0:
            lines.append(f"  auto {iterator_name} = MII;")
        else:
            prev = f"LocalMII{index - 1}"
            lines.append(f"  auto {iterator_name} = {prev};")
            lines.append(f"  ++{iterator_name};")
            lines.append(f"  if ({iterator_name} == MIE)")
            lines.append(f"    return {miss_return};")
        lines.append(f"  auto &{bind} = *{iterator_name};")

        if "predicate" in item:
            predicate = item["predicate"]
            lines.append(f"  if (!{bind}.{predicate}())")
            lines.append(f"    return {miss_return};")
        elif "opcode" in item:
            lines.append(f"  if ({bind}.getOpcode() != X86::{item['opcode']})")
            lines.append(f"    return {miss_return};")
        else:
            lines.append(f"  switch ({bind}.getOpcode()) {{")
            for opcode in item["opcode_any"]:
                lines.append(f"  case X86::{opcode}:")
                lines.append("    break;")
            lines.append("  default:")
            lines.append(f"    return {miss_return};")
            lines.append("  }")

        for capture in item.get("capture", []):
            lines.extend(emit_capture(bind, capture, miss_return))
        for req in item.get("require", []):
            lines.extend(emit_operand_check(bind, req, miss_return))

    if erases_current:
        lines.append("  auto NextMII = MII;")
        lines.append("  ++NextMII;")
    for action in rule["action"].get("erase", []):
        lines.append(f"  {action}.eraseFromParent();")
    for action in rule["action"].get("set_imm", []):
        lines.append(
            f"  {action['inst']}.getOperand({action['operand']}).setImm("
            f"{action['from_capture']});"
        )
    if erases_current:
        lines.append("  MII = NextMII;")
        lines.append("  return GeneratedInstructionRuleResult::Advanced;")
    else:
        lines.append("  return GeneratedInstructionRuleResult::Matched;")
    lines.append("}")
    lines.append("")
    return lines


def emit_block_end_match(rule: Dict) -> List[str]:
    name = rule["name"].replace("-", "_")
    pattern = rule["pattern"][0]
    bind = pattern["bind"]
    lines = [
        f"bool match_{name}(CgBasicBlock &MBB) {{",
        "  if (MBB.empty())",
        "    return false;",
        f"  auto &{bind} = MBB.back();",
    ]
    if "predicate" in pattern:
        predicate = pattern["predicate"]
        lines.append(f"  if (!{bind}.{predicate}())")
        lines.append("    return false;")
    for req in pattern.get("require", []):
        lines.extend(emit_operand_check(bind, req, "false"))
    for item in rule.get("when", []):
        if item["kind"] == "target_is_next_block":
            inst = item["inst"]
            operand = item["operand"]
            lines.extend(
                [
                    f"  CgBasicBlock *TargetBB = {inst}.getOperand({operand}).getMBB();",
                    "  if (TargetBB->getNumber() != MBB.getNumber() + 1)",
                    "    return false;",
                ]
            )
        else:
            raise ValueError(f"Unsupported rule condition: {item}")
    for action in rule["action"].get("erase", []):
        lines.append(f"  {action}.eraseFromParent();")
    lines.append("  return true;")
    lines.append("}")
    lines.append("")
    return lines


def emit_dispatch(data: Dict) -> List[str]:
    lines = [
        "namespace {",
        "",
        "enum class GeneratedInstructionRuleResult {",
        "  NoMatch,",
        "  Matched,",
        "  Advanced,",
        "};",
        "",
    ]
    instruction_rules = [rule for rule in data["rules"] if rule["stage"] == "instruction"]
    block_rules = [rule for rule in data["rules"] if rule["stage"] == "block_end"]

    for rule in instruction_rules:
        lines.extend(emit_instruction_match(rule))
    for rule in block_rules:
        lines.extend(emit_block_end_match(rule))

    lines.extend(
        [
            "GeneratedInstructionRuleResult tryGeneratedInstructionRules(",
            "    CgBasicBlock &MBB, CgBasicBlock::iterator &MII) {",
        ]
    )
    for rule in instruction_rules:
        lines.append(
            f"  if (auto Result = match_{rule['name'].replace('-', '_')}(MBB, MII);"
        )
        lines.append("      Result != GeneratedInstructionRuleResult::NoMatch)")
        lines.append("    return Result;")
    lines.extend(["  return GeneratedInstructionRuleResult::NoMatch;", "}", ""])

    lines.extend(["bool tryGeneratedBlockEndRules(CgBasicBlock &MBB) {"])
    for rule in block_rules:
        lines.append(f"  if (match_{rule['name'].replace('-', '_')}(MBB))")
        lines.append("    return true;")
    lines.extend(["  return false;", "}", "", "} // namespace", ""])
    return lines


def write_text(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rules", required=True)
    parser.add_argument("--out-inc", required=True)
    parser.add_argument("--out-report", required=True)
    args = parser.parse_args()

    rules_path = pathlib.Path(args.rules)
    data = load_rules(rules_path)
    report_lines, conflicts = validate_rules(data)

    if conflicts:
        write_text(pathlib.Path(args.out_report), "\n".join(report_lines) + "\n")
        for item in conflicts:
            print(item, file=sys.stderr)
        return 1

    inc_lines = emit_file_header() + emit_dispatch(data)
    write_text(pathlib.Path(args.out_inc), "\n".join(inc_lines))
    write_text(pathlib.Path(args.out_report), "\n".join(report_lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
